server:
  port: 8070
  tomcat:
    uri-encoding: UTF-8
spring:
  redis:
#    cluster:
#      nodes: 10.13.199.89:6372,10.13.199.89:6373,10.13.199.89:6374,10.13.199.89:6375,10.13.199.89:6376,10.13.199.89:6377
    jedis:
      pool:
        max-active: 2000
        min-idle: 8
        max-wait: 20ms
    timeout: 5000ms
    host: 127.0.0.1
    port: 6379

# clickhouse
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://172.30.154.50:8123/analysis
    username:
    password:
mybatis:
  mapper-locations: classpath:mapping/*.xml

#启动SeimiCrawler
seimi:
  crawler:
    enabled: true
    names: basic